### ISSUE TITLE
Character Card link to full page description is disorienting

### ISSUE THREAD

**Issue by Serpensor** [WTIGER001/sfcmap#2]
"Character Index"
When clicking in the center of a card (on an image) it links you to a full page.  This is disorienting.  I recommend the following behavior.

1. Remove behavior of clicking on name at top of card - make it have no affect

2. Make clicking on the image toggle from either; a. full image or, b. animate up/down more detail that fills up 2/3 of the image.  Keep the left/right arrows for the different categories.

3. No need for the full page link

**Comment by WTIGER001** [comment]
I am confused...how do you edit the character and see the full screen variant then?

**Comment by Serpensor** [comment]
Hmmm....  I dunnno.  I'm just a stupid user and don't really know what I'm
talking about - but I'm damn sure gonna cry like a baby if I don't get what
I want - even if I don't know what that is.

Sorry - just thinking about Dave Grover today
